name = "main"
name_pretty = "Artix Main Menu"
action = "%VALUE%"

[[entries]]
text = "1. Apps"
subtext = "Open Walker"
value = "walker"
icon = "/home/glodanif/.local/share/assets/apps.png"

[[entries]]
text = "2. Audio Sinks"
subtext = "Switch to audio sink"
value = "switch-audio-sink"
icon = "/home/glodanif/.local/share/assets/audio.png"

[[entries]]
text = "3. About"
subtext = "fastfetch"
value = "run-and-wait fastfetch"
icon = "/home/glodanif/.local/share/assets/artix-logo.png"

[[entries]]
text = "4. Reboot into Windows"
subtext = "Boot Windows once"
value = "hyprland-power reboot-windows"
icon = "/home/glodanif/.local/share/assets/artix-logo.png"

[[entries]]
text = "5. Power Menu"
subtext = "Power off/Log out/Reboot/Lock"
value = "power-menu"
icon = "/home/glodanif/.local/share/assets/power-on.png"

