name = "scripts"
name_pretty = "Scripts"
icon = "application-x-executable"
action = "ghostty -e sh -c '%VALUE%'"

[[entries]]
text = "Start screen recording"
subtext = "screenrecord on"
value = "screenrecord on"

[[entries]]
text = "Start screen recording with audio"
subtext = "screenrecord on --audio"
value = "screenrecord on --audio"

[[entries]]
text = "System update"
subtext = "sys-update"
value = "run-and-wait sys-update"

[[entries]]
text = "System backup"
subtext = "sys-backup"
value = "run-and-wait sys-backup"

[[entries]]
text = "Install package"
subtext = "install-package"
value = "install-package"

[[entries]]
text = "Install AUR package"
subtext = "install-aur-package"
value = "install-aur-package"

[[entries]]
text = "Uninstall package"
subtext = "uninstall-package"
value = "uninstall-package"

[[entries]]
text = "Start SSH"
subtext = "sudo rc-service sshd start"
value = "run-and-wait start-ssh"

[[entries]]
text = "Power menu"
subtext = "power-menu"
value = "power-menu"

[[entries]]
text = "Start VPN"
subtext = "vpn-run on"
value = "run-and-wait vpn-run on"

