name = "scripts"
name_pretty = "Scripts"
icon = "application-x-executable"
action = "run-and-wait '%VALUE%'"

[[entries]]
text = "Start screen recording"
subtext = "screenrecord on"
value = "screenrecord on"

[[entries]]
text = "Start screen recording with audio"
subtext = "screenrecord on --audio"
value = "screenrecord on --audio"

[[entries]]
text = "System update"
subtext = "sys-update"
value = "sys-update"

[[entries]]
text = "System backup"
subtext = "sys-backup"
value = "sys-backup"

[[entries]]
text = "Install package"
subtext = "install-package"
value = "install-package"

[[entries]]
text = "Install AUR package"
subtext = "install-aur-package"
value = "install-aur-package"

[[entries]]
text = "Uninstall package"
subtext = "uninstall-package"
value = "uninstall-package"

[[entries]]
text = "Artix doctor"
subtext = "artix-doctor"
value = "artix-doctor"

[[entries]]
text = "Start VPN"
subtext = "vpn-run on"
value = "vpn-run on"

