name = "scripts"
name_pretty = "Scripts"
icon = "application-x-executable"
action = "%VALUE%"

[[entries]]
text = "Start screen recording"
subtext = "screenrecord on"
value = "screenrecord on"

[[entries]]
text = "Start screen recording with audio"
subtext = "screenrecord on --audio"
value = "screenrecord on --audio"

[[entries]]
text = "Artix doctor"
subtext = "artix-doctor"
value = "run-and-wait artix-doctor"

[[entries]]
text = "Start VPN"
subtext = "vpn-run on"
value = "run-and-wait vpn-run on"

