# Core
hwdec=vaapi
hwdec-codecs=hevc,h264,av1,vp9
vo=gpu-next
gpu-api=vulkan
video-sync=display-resample
framedrop=vo
osd-font='Lato'
volume=50
save-position-on-quit=yes
autofit-larger=90%x90%

# Seeking - this is what fixes your deadlock
hr-seek=yes
hr-seek-framedrop=yes
demuxer-max-bytes=150MiB
demuxer-readahead-secs=20

# Scaling - gpu-hq is overkill for a TV, this is a sane middle ground
scale=spline36
cscale=spline36
dscale=mitchell
dither-depth=auto
correct-downscaling=yes
linear-downscaling=no
sigmoid-upscaling=yes
deband=yes

# Loop
loop-file=inf

autocreate-playlist=same
drag-and-drop=replace

