exec-once = pgrep -x pipewire > /dev/null || pipewire
exec-once = pgrep -x wireplumber > /dev/null || wireplumber  
exec-once = pgrep -x pipewire-pulse > /dev/null || pipewire-pulse
exec-once = hyprpaper
exec-once = hypridle
exec-once = elephant
exec-once = waybar
exec-once = walker --gapplication-service
exec-once = mako
exec-once = keyboard-watch
exec-once = wl-clip-persist --clipboard regular
exec-once = wl-paste --watch cliphist store
exec-once = sleep 1 && /usr/lib/xdg-desktop-portal-hyprland
exec-once = sleep 2 && /usr/lib/xdg-desktop-portal --replace
exec-once = profile-io restore 2000

