hl.on("hyprland.start", function()
	hl.exec_cmd("pgrep -x pipewire > /dev/null || pipewire")
	hl.exec_cmd("pgrep -x wireplumber > /dev/null || wireplumber")
	hl.exec_cmd("pgrep -x pipewire-pulse > /dev/null || pipewire-pulse")
	hl.exec_cmd("hyprpaper")
	hl.exec_cmd("hypridle")
	hl.exec_cmd("elephant")
	hl.exec_cmd("waybar")
	hl.exec_cmd("walker --gapplication-service")
	hl.exec_cmd("swaync")
	hl.exec_cmd("headphones-watch")
	hl.exec_cmd("urgent-watch")
	hl.exec_cmd("usb-watch")
	hl.exec_cmd("wl-clip-persist --clipboard regular")
	hl.exec_cmd("wl-paste --watch cliphist store")
	hl.exec_cmd("sleep 1 && /usr/lib/xdg-desktop-portal-hyprland")
	hl.exec_cmd("sleep 2 && /usr/lib/xdg-desktop-portal --replace")
	hl.exec_cmd("monitors-layout-restore")
	hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")
	hl.exec_cmd("gnome-keyring-daemon --start --components=secrets,pkcs11")
	hl.exec_cmd("sh -c 'mkdir -p $XDG_RUNTIME_DIR/gcr && /usr/lib/gcr-ssh-agent --base-dir $XDG_RUNTIME_DIR/gcr'")
	hl.exec_cmd("solaar --window=hide")
	hl.exec_cmd("sleep 1 && discord --start-minimized")
	hl.exec_cmd("sleep 1 && slack --startup")
	hl.exec_cmd("Telegram -startintray")
	hl.exec_cmd("voxtype daemon")
	hl.exec_cmd("syncthing")
	hl.exec_cmd("mic-pico-sync")
end)
