background {
    color = rgba(12, 12, 12, 1)
}

label {
    monitor =
    text = Locked
    color = rgba(255, 255, 255, 0.8)
    font_size = 48
    font_family = Sans
    position = 0, 100
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2
    outer_color = rgba(255, 255, 255, 0.3)
    inner_color = rgba(30, 30, 30, 0.8)
    font_color = rgba(255, 255, 255, 1)
    placeholder_text = Password
    position = 0, -100
    halign = center
    valign = center
}
