plugin {
    hy3 {
        tabs {
            border_width = 2
            radius = 10
            col.active = rgba(9370da77)
            col.active.border = rgba(9370daaa)
            col.inactive = rgba(59595977)
            col.inactive.border = rgba(595959aa)
            col.urgent = rgba(ff5b6177)
            col.urgent.border = rgba(ff5b61aa)
        }

        autotile {
            enable = true
            trigger_width = 1300
            trigger_height = 500
        }
    }
}

