###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

# Set programs that you use
$terminal = ghostty
$fileManager = thunar
$menu = walker
$browser = brave
$tasks = btop

